### ISSUE TITLE
markedjs vulnerability

### ISSUE THREAD

**Issue by paidforby** [sudomesh/peoplesopen-front#13]
Recent update to using gulp method of building peoplesopen-front as a static site produced a vulnerability with a npm package named markedjs. Update to newer version in package.json and test build process.

**Comment by jnny** [comment]
updated package.json with current versions of marked and gulp-sass, updated node-sass, converted package-lock.json to npm-shrinkwrap.json, and successfully rebuilt. security warnings no longer appear. closin'!
