### ISSUE TITLE
workshop page broken

### ISSUE THREAD

**Issue by jhpoelen** [sudomesh/peoplesopen-front#15]
![screenshot from 2018-02-18 18-37-25](https://user-images.githubusercontent.com/1084872/36360655-e1819768-14da-11e8-9f4f-13d8fc955518.png)

**Comment by bennlich** [comment]
All the html urls are broken. Forgot to edit that part of nginx config lol.

**Comment by bennlich** [comment]
This one is especially problematic because we left in the rule that rewrites /workshop -> /workshop.html

**Comment by jhpoelen** [comment]
; ) let me know if you need help

**Comment by jhpoelen** [comment]
(btw - really like the new .md based pages, makes easier to edit etc)

**Comment by bennlich** [comment]
Yay. Will fix when next am at computer... So later this eve. Feel free to
fix sooner.

**Comment by jhpoelen** [comment]
Just remove the workshop redirect that broke the link from the homepage. Hoping you can help setup a general rule to html redirects.

**Comment by bennlich** [comment]
👍🏽

**Comment by bennlich** [comment]
Thank you whoever fixed this.
