### ISSUE TITLE
Finish migrating html -> markdown

### ISSUE THREAD

**Issue by bennlich** [sudomesh/peoplesopen-front#18]
The developer, documentation, how-to-help, and join-the-network files are still html dumped inside of markdown files. As much as possible, it would help to rewrite this html as real markdown. See [the workshop markdown](https://raw.githubusercontent.com/sudomesh/peoplesopen-front/master/src/workshop/index.md) for an example.

**Comment by jnny** [comment]
this was open too long and bugged me, so... done :)

**Comment by bennlich** [comment]
Ur on a f*kin roll
