### ISSUE TITLE
user flows

### ISSUE THREAD

**Issue by wrought** [sudomesh/peoplesopen-front#2]
How will users interact with this page?

We have two primary actions already "Join" i.e. buy a node, and "Help" i.e. participate in the group somehow, look at our wishlist, join the newsletter, etc.

Need to grow content out on the landing page.

**Comment by paidforby** [comment]
Two issues (#7 and #9) with similar comments have since been closed, I'm closing this to clean up peoplesopen-front issues. If anyone disagrees and thinks this topic has not been sufficiently addressed, please open a new issue with more specific complaints.
