### ISSUE TITLE
Explain what join the network means

### ISSUE THREAD

**Issue by jefdaj** [sudomesh/peoplesopen-front#7]
It would be cool if the "Join the network" link on the homepage went to a quick explanation of what that means in material terms. Something like "Set up a home node ($20 and half hour work), help other people set up nodes (meet on a Sunday), special bonus awesome for having a house on a hill, ..." Related to [#5](https://github.com/sudomesh/peoplesopen-front/issues/5). There could also be a link to the map but with some context like "See current nodes/sign up for a node setup party"

**Comment by jhpoelen** [comment]
Related to #2 and #9 . @gcgallo @jefdaj would it make sense to merge #7 and #9 ?

**Comment by gcgallo** [comment]
Agreed. I didn't notice that issue. Go ahead and merge them.

**Comment by jhpoelen** [comment]
@gcgallo said "Instead of having the "Join the Network" link jump directly to the map with no explanation, have it goto another page (or a different part of the front page) that explains a bit about the network, getting a node, setting up an antennae, making a donation, and then link to the map."

**Comment by paidforby** [comment]
"Join the Network" has since been redirected to https://peoplesopen.net/join-the-network.html. Various additions have been made since that page to address @gcgallo's suggestion.

**Comment by jnny** [comment]
@jefdaj @paidforby added a [node request form](https://peoplesopen.net/node-request.html) (unfortunately a googleform...) linked to from [join the network](https://peoplesopen.net/join-the-network.html), with the following text: 

> There are several ways to join the network, and hosting a node is one of them. Home Nodes cost $20 and are simple to flash and set up. Come to a sudomesh Tuesday evening meeting at the Omni Commons or an upcoming workshop to flash a Home Node with the SudoWRT firmware and take it home - if it can see another node on the network, it can share that connection and any available Internet bandwidth; if it can't, you can connect to the mesh and extend the peoplesopen.net signal by connecting it to your existing home router.
> Extender Nodes cost between $60-80 and operate on a higher frequency that enables us to make high-speed point-to-point links across long distance - so long as there's line of sight. If you have an available rooftop (ideally on a hill) with line of sight to one of our backbone nodes, we'll reach out to schedule a site visit and/or Sunday afternoon node mount! 
We're an all-volunteer group and still working out some details before we go fully and loudly public, so please be patient - or better yet, come to a workshop and become a volunteer!
