### ISSUE TITLE
Set up etherpad-lite instance at peoplesopen.net/notes

### ISSUE THREAD

**Issue by jnny** [sudomesh/peoplesopen-front#8]
source and readme at https://github.com/ether/etherpad-lite

**Comment by paidforby** [comment]
etherpad-lite instance is running on the sudomesh server with a new MySQL database. The instance can be reached at peoplesopen.net:9001 or peoplesopen.net/pad. Need to make sure it runs on startup. We also may need to consider implementing logrotation.
