### ISSUE TITLE
Direct "Join the Network" to a different page

### ISSUE THREAD

**Issue by gcgallo** [sudomesh/peoplesopen-front#9]
Instead of having the "Join the Network" link jump directly to the map with no explanation, have it goto another page (or a different part of the front page) that explains a bit about the network, getting a node, setting up an antennae, making a donation, and then link to the map.

**Comment by jhpoelen** [comment]
Sounds like a plan - little more action oriented that an open-ended map. Related to #2

**Comment by jhpoelen** [comment]
Merging to #7 .
